apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: sweetiq-tasker-sandbox-east
  name: workforce-fake-service-deployment
  labels:
    app: workforce-fake-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workforce-fake-service
    spec:
      containers:
      - args:
        image: quay.io/gannett/tasker-fake-service
        env:
        - name: TASKER_URL
          value: "https://workforce-staging.swiq3.com/"
        - name: AUTH0_TOKEN
          valueFrom:
            secretKeyRef:
             name: app-data
             key: auth0_client_id
        - name: AUTH0_SECRET
          valueFrom:
            secretKeyRef:
              name: app-data
              key: auth0_secret
        name: app
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: quay-secret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: sweetiq-tasker-sandbox-east
  name: workforce-fake-service-service
  labels:
    app: workforce-fake-service-service
spec:
  type: "LoadBalancer"
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    app: workforce-fake-service
