apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workforce-fake-service-mongo-deployment
  labels:
    app: workforce-fake-service-mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workforce-fake-service-mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: data
      restartPolicy: Always
      volumes:
      - name: data
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: workforce-fake-service-mongo-service
  labels:
    app: workforce-fake-service-mongo-service
spec:
  type: "LoadBalancer"
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: workforce-fake-service-mongo
status:
  loadBalancer: {}
